import os
from dotenv import load_dotenv

load_dotenv()

DISCORD_APPLICATION_TOKEN = os.getenv('DISCORD_APPLICATION_TOKEN')
DISCORD_APPLICATION_CLIENT_ID = os.getenv('DISCORD_APPLICATION_CLIENT_ID')
DISCORD_APPLICATION_CLIENT_SECRET = os.getenv('DISCORD_APPLICATION_CLIENT_SECRET')
DISCORD_APPLICATION_PUBLIC_KEY = os.getenv('DISCORD_APPLICATION_PUBLIC_KEY')